### ISSUE TITLE
[TT-004/001] Categorization Backend

### ISSUE THREAD

**Issue by NarrowCode** [sw21-tug/Team_02#67]
subtask of #4 

**Details:**

Project consists of:
- ID (Auto-Increment)
- Name (String, Max. 40 Characters)
- Color (Hex String)

**Tasks:**

- [x] create additional database table "projects"
- [x] add functionality to insert new projects into the database
- [x] add functionality to edit projects in the database (project name)
- [x] add functionality to delete projects from the database
