### ISSUE TITLE
[TT-004/002] Categorization Frontend

### ISSUE THREAD

**Issue by NarrowCode** [sw21-tug/Team_02#69]
subtask of #4 

**Details:**
For visual details, see mockup in #4.

**Tasks:**
- [x] user can define projects
- [x] user can delete projects
- [ ] Items can be indented (see description in #4) - not finished in this implementation
- [ ] Implement UI Flow as shown in mockup #4 - modify not yet implemented
