### ISSUE TITLE
[TT-005/002] Task categorization frontend

### ISSUE THREAD

**Issue by NarrowCode** [sw21-tug/Team_02#71]
subtask of #5 

**Details:**
For visual details, see mockup in #5.
The "Inbox" will act as a virtual category, essentially grouping all tasks that are not assigned to a user-defined project.

**Tasks:**
- [ ] Adapt the "Add Task" and "Modify Task" dialogs to add the combobox for project selection
- [ ] Implement "popup" that allows project selection when the user clicks on the project.
- [ ] "Inbox" on top of user-defined projects as "virtual project"
- [ ] Default project = "Inbox"
- [ ] User cannot select nothing
